### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/docs#125]
The existing structure of the documentation was moved over from gitbook where it evolved organically over years. Consequently, some content is redundant across multiple chapters and some content should be moved to the website instead of docs (e.g. community and network primer chapters). The rule of thumb should be **website should sell and entertain while documentation should educate people which are already convinced to use Oasis platform**.

Documentation faces a standard audience VS products challenge, where the audience are:
- users
- node operators
- dApp developers
- core contributors.

And the products are (at least):
- Emerald, Cipher, Sapphire ParaTimes
- the Oasis network including Amber, Cobald, Damask upgrades
- oasis-node, oasis CLI
- oasis web and browser extension wallets
- typescript and golang grpc clients
- runtime SDK for rust
- emerald web3 gateway, rosetta gateway, blockscout
- ledger nano app

A product can have features corresponding to multiple audiences (e.g. Emerald or Cipher touches users - token transfers, node operators - running a paratime node, dApp developers - building dApps on them).

All docs changes must be backward compatible by adding static routes to the new URLs.

**Comment by gw0** [comment]
We also have a third "network" dimension (at least regarding versions and configuration) -- Mainnet and Testnet. The "Consensus layer" could also be thought of as a product.

I would argue that the "users" and "dApp developers" audiences should be split per-ParaTime, because the usage and development stacks for Emerald and Cipher are so drastically different there is not much in common.

My intuition would be to group around Consensus/Emerald/Cipher. For example:
- Consensus layer: Rosetta gateway, Oasisscan Block Explorer, Oasis Monitor Block Explorer
- Emerald ParaTime: Emerald usage tutorial (Metamask), Emerald dApp development tutorial (Truffle), Emerald Web3 gateway, Emerald Block Explorer (Blockscout)
- Cipher ParaTime: Cipher usage tutorial, Cipher dApp development tutorial
- Oasis Network: Mainnet/Testnet parameters with ParaTime config (e.g. Metamask settings), all upgrade instructions, gRPC endpoint usage tutorial (Typescript/Golang gRPC clients)

**Comment by tjanez** [comment]
I think we should approach this incrementally, i.e. in evolutionary steps.

I think the first step is to split out the developer parts of our general docs into its own group using [Docusaurus' Multiple sidebars feature](https://docusaurus.io/docs/sidebar/multiple-sidebars).

**Comment by matevz** [comment]
Fixed in #200.
